'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminImagePicker from './AdminImagePicker';
export default function ProductCreateForm({categories}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''); const router=useRouter();
 async function submit(e){e.preventDefault();if(busy)return;const f=e.currentTarget,fd=new FormData(f);const name=String(fd.get('name')||'').trim(),slug=String(fd.get('slug')||'').trim(),cat=String(fd.get('categoryId')||''),price=Number(fd.get('basePrice')),image=String(fd.get('image')||'').trim();
  if(!name){setError('اكتب اسم المنتج.');return} if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)){setError('اكتب Slug صحيحاً مثل super-hilton.');return} if(!cat){setError('اختر النوع / المنشأ.');return} if(!Number.isFinite(price)||price<0){setError('اكتب سعر المتر المربع بشكل صحيح.');return} if(!image){setError('أضف صورة رئيسية للمنتج.');return}
  setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/admin/products',{method:'POST',body:fd,headers:{'x-requested-with':'fetch'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'تعذر إضافة المنتج.');f.reset();setSuccess('تمت إضافة المنتج بنجاح.');router.refresh()}catch(err){setError(err?.message||'تعذر إضافة المنتج. حاول مرة أخرى.')}finally{setBusy(false)}}
 return <form onSubmit={submit} noValidate data-no-global-loading="true"><div className="admin-form-grid"><div className="field"><label>الاسم</label><input name="name" disabled={busy}/></div><div className="field"><label>رابط المنتج (Slug)</label><input name="slug" placeholder="super-hilton" disabled={busy}/><span className="small">للرابط فقط.</span></div><div className="field full"><label>الوصف</label><textarea name="description" rows="4" disabled={busy}/></div><div className="field"><label>النوع / المنشأ</label><select name="categoryId" disabled={busy}><option value="">اختر النوع</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label>سعر المتر المربع (₪/م²)</label><input type="number" step="0.01" min="0" name="basePrice" disabled={busy}/><span className="small">السعر النهائي للزبون يقرب تلقائياً لأقرب 5 ₪.</span></div><div className="field"><label>سعر سابق للمتر المربع (اختياري)</label><input type="number" step="0.01" min="0" name="compareAt" disabled={busy}/></div><AdminImagePicker name="image" label="الصورة الرئيسية — ارفع صورة أو التقطها الآن"/></div><div className="admin-checkboxes"><label><input type="checkbox" name="featured" value="true"/> مميز</label><label><input type="checkbox" name="bestseller" value="true"/> الأكثر مبيعاً</label><label><input type="checkbox" name="isNew" value="true"/> جديد</label></div>{error&&<div className="form-error" role="alert">{error}</div>}{success&&<div className="notice success-notice">{success}</div>}<button className="btn btn-primary" disabled={busy}>{busy?'جاري الإضافة...':'إضافة المنتج'}</button></form>
}
